// ⚠️  Auto-generated by scripts/apply-branding.mjs — do not edit directly.
// To update branding, edit app.config.mjs and run: pnpm run brand

export const APP_NAME           = '天工AI'
export const APP_ID             = 'cn.toguide.tiangong'
export const FIREWALL_RULE_NAME = 'TianGong'
